spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/test
    username: root
    password: "admin"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop